name: polyp-tf1-gpu
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates
  - certifi=2020.6.20
  - cudatoolkit
  - cudnn=7.6.5
  - expat=2.2.9
  - ffmpeg=4.0
  - intel-openmp=2020.1
  - jpeg=9b
  - kiwisolver=1.2.0
  - libffi=3.2.1
  - libopencv=3.4.2
  - libpng=1.6.37
  - libtiff=4.1.0
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - matplotlib=3.2.2
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - numpy=1.18.5
  - numpy-base=1.18.5
  - opencv=3.4.2
  - openssl=1.0.2u
  - pcre=8.44
  - pip=20.1.1
  - pixman=0.40.0
  - python=3.7.0
  - python-dateutil
  - qt=5.9.6
  - setuptools=47.3.1
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.32.3
  - tk=8.6.10
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - absl-py==0.9.0
    - astor==0.8.1
    - cachetools==4.1.1
    - chardet==3.0.4
    - gast==0.2.2
    - google-auth==1.18.0
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - grpcio==1.30.0
    - idna==2.10
    - importlib-metadata==1.7.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - lxml==4.5.1
    - markdown==3.2.2
    - oauthlib==3.1.0
    - opt-einsum==3.2.1
    - protobuf==3.12.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - tensorboard==1.15.0
    - tensorflow-estimator==1.15.1
    - tensorflow-gpu==1.15.0
    - termcolor==1.1.0
    - tqdm==4.47.0
    - urllib3==1.25.9
    - werkzeug==1.0.1
    - wrapt==1.12.1
    - zipp==3.1.0

